#!/usr/bin/env bash
# =========================================
# .FILE
#   sfy
#
# .SYNOPSIS
#   Symfony CLI helper (with less typing)
#
# .DESCRIPTION
#   Wrapper script for frequently used Symfony CLI commands
#   to reduce keystrokes and simplify development.
#
# .PARAMETER command
#   The Symfony command to run (e.g., console, serve, etc.)
#
# .INPUTS
#   None
#
# .OUTPUTS
#   Depends on the Symfony command used
#
# .NOTES
#   Version       : 1.0
#   Author        : @ZouariOmar <zouariomar20@gmail.com>
#   Created       : 2025-10-11
#   Change Log    : Initial version
#
# .EXAMPLE
#   ./sfy cc   # Runs 'symfony console cache:clear'
# =========================================

# Load custom colors
[[ -s ${HOME}/.bash/.bash_colors ]] && source "${HOME}/.bash/.bash_colors"

# Configuration
EXIT_SUCCESS=0
EXIT_FAILED=1
SYMFONY_BIN="symfony"
CONSOLE_BIN="php bin/console"

# Aliases for common commands
declare -A COMMANDS
COMMANDS["cc"]="${CONSOLE_BIN} cache:clear"
COMMANDS["ss"]="${SYMFONY_BIN} server:start"
COMMANDS["sst"]="${SYMFONY_BIN} server:stop"
COMMANDS["mm"]="${CONSOLE_BIN} make:migration"
COMMANDS["dmm"]="${CONSOLE_BIN} doctrine:migrations:migrate"
COMMANDS["me"]="${CONSOLE_BIN} make:entity"
COMMANDS["mc"]="${CONSOLE_BIN} make:controller"
COMMANDS["mf"]="${CONSOLE_BIN} make:form"
COMMANDS["ma"]="${CONSOLE_BIN} make:auth"
COMMANDS["mac"]="${CONSOLE_BIN} make:admin:crud"

# Main func to execute shortcuts
function run_cmd() {
  if [[ $1 == "--help" ]] || [[ $1 == "-h" ]]; then
    help // + EXIT_SUCCESS
  fi

  local key="$1"
  shift

  if [[ -n "${COMMANDS[${key}]}" ]]; then
    ${COMMANDS[${key}]} "$@"
    exit ${EXIT_SUCCESS}
  fi

  usage "${RED}[ERROR] Unknown shortcut ${key}${RESET}"
  exit ${EXIT_FAILED}

}

usage() {
  if [ ! -z "$1" ]; then
    echo -e "$1"
  fi
  echo -e "${BLUE}[INFO]Try './sfy --help' for more information.${RESET}"
}

help() {
  echo -e "${YELLOW}[FILE]${RESET}
  sfy
${YELLOW}[LINK]${RESET}
  https://github.com/ZouariOmar
${YELLOW}[BRIEF]${RESET}
  Symfony CLI helper (with less typing)
${YELLOW}[USAGE]${RESET}
  ./sfy cc        -- Runs 'symfony console cache:clear'
${YELLOW}[OPTIONS]${RESET}
  cc  -- ${CONSOLE_BIN} cache:clear
  ss  -- ${SYMFONY_BIN} server:start
  sst -- ${SYMFONY_BIN} server:stop
  mm  -- ${CONSOLE_BIN} make:migration
  dmm -- ${CONSOLE_BIN} doctrine:migrations:migrate
  me  -- ${CONSOLE_BIN} make:entity
  mc  -- ${CONSOLE_BIN} make:controller
  mf  -- ${CONSOLE_BIN} make:form
  ma  -- ${CONSOLE_BIN} make:auth
  mac -- ${CONSOLE_BIN} make:admin:crud

${YELLOW}[VERSION]${RESET}
  1.0
${YELLOW}[AUTHOR]${RESET}
  @ZouariOmar <zouariomar20@gmail.com>
${YELLOW}[CREATED]${RESET}
  11/10/2025
${YELLOW}[CHANGELOG]${RESET}
  1.0"
  exit ${EXIT_SUCCESS}
}

if [[ $# -lt 1 ]]; then
  usage "${RED}[ERROR] sfy: you must specify the option with there args.${RESET}"
  exit 1
fi

run_cmd "$@"
